### ISSUE TITLE
cant create more than 5 streams

### ISSUE THREAD

**Issue by rasoolkhalifa** [OPENSPHERE-Inc/branch-output#11] opened 2024-08-17 11:53 UTC
When I try connect to more than 5 streams the 6th one does not connect whats the problem?

**Comment by hanatyan128** [comment] 2024-08-18 01:27
> When I try connect to more than 5 streams the 6th one does not connect whats the problem?

If you are using a hardware encoder such as NVENC, be aware that there may be a limit to the number of concurrent sessions.
https://developer.nvidia.com/video-encode-and-decode-gpu-support-matrix-new#Encoder

You can investigate the cause yourself by checking the OBS logs.
Help Menu→Log Files→View Current Log

Since I am able to connect 6 streams in the environment at hand (GeForceRTX 3080), the issue is closed as it does not appear to be a plug-in problem at this time.

**Closed by hanatyan128** 2024-08-18 01:27 UTC
